#Le but de notre docker-compose va être de configurer l'execution de nos trois services dans des conteneurs : Prometheus, Grafana et Flask-API.
#On va ensuite les faire communiquer ensemble dans un network, qu'on va ici appeler my_network.
#Chacun des services va être mappé sur un port distinct, avec lequel nous pourront communiquer par la suite.

version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: projetv2-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my_network

  grafana:
    image: grafana/grafana:latest
    container_name: projetv2-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - my_network

  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projetv2-flask-api
    ports:
      - "5000:5000"
    volumes:
      - ./donnees_brutes:/donnees_brutes
      - ./test.py:/app/test.py
    networks:
      - my_network
    environment:
      - FLASK_APP=test.py
      - FLASK_RUN_HOST=0.0.0.0

networks:
  my_network:
    driver: bridge